### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DavAug**
Adding reference to chi

### CODE REVIEW

**Review by martinjrobins — CHANGES_REQUESTED** [review]
Thanks @DavAug . I think this would live in "Libraries"? was thinking that the group software projects would go in "SABS-R3 Software Projects".

**Comment by martinjrobins** [comment]
Can you put in a PR (or add to the same PR) to https://github.com/DavAug/filter-inference as well? (Under publications)?

**Comment by DavAug** [comment]
> Thanks @DavAug . I think this would live in "Libraries"? was thinking that the group software projects would go in "SABS-R3 Software Projects".

Ok let me move chi to the library and add the epidemiology project to the group projects

**Comment by martinjrobins** [comment]
Thanks @DavAug ! I'll merge this in now

**Review by martinjrobins — APPROVED** [review]
looks great!

**Pull request merged**
